# Generated by Django 3.2.5 on 2021-07-02 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesTitle', models.CharField(max_length=255)),
                ('quesDesc', models.TextField(default='')),
                ('sampleInput', models.TextField(default='')),
                ('sampleOutput', models.TextField(default='')),
                ('successfulAttempts', models.IntegerField(default=0)),
                ('numberOfAttempts', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('py', 'Python')], max_length=3)),
                ('code', models.TextField(default='', max_length=10000000)),
                ('attempt', models.IntegerField(default=0)),
                ('status', models.CharField(default='NA', max_length=5)),
                ('submission_time', models.CharField(default='', max_length=15)),
                ('score', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('quesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.question')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submissions',
                'verbose_name_plural': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=10)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('totalScore', models.IntegerField(default=0)),
                ('junior', models.BooleanField(default=True)),
                ('correctly_answered', models.IntegerField(default=0)),
                ('chances', models.IntegerField(default=3)),
                ('latestSubTime', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
